### ISSUE TITLE
Waukeen Promenade Bank

### ISSUE THREAD

**Issue by rubyFeedback** [Austin-BG/HTaM#7]
Could the readme explain where the bank could be found?

I am not seeing it on the map, so perhaps I did not install the mod properly. That's why it would be nice if the main README could mention this clearly. Thanks for reading!

**Comment by Austin-BG** [comment]
Hello! The bank is located on the Waukeen Promenade in the lower right part of the location, it is marked with a marker. But in order for it to appear correctly, after installing this component, it is necessary to start the game from the moment BEFORE the first loading of the Promenade area (that is, before leaving the Irenicus dungeon). This applies to any mods that change areas.

**Comment by rubyFeedback** [comment]
I found it today. I think there was a conflict with other mods, which was why it did not show up.

I finally upgraded the main game and I think I solved some of the installation orders I used to have, so that part works.
